//
// Calldata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Calldata: Codable, Hashable {

    /** Prefixed (cb_) Base64Check encoded byte array */
    public var calldata: String

    public init(calldata: String) {
        self.calldata = calldata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case calldata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(calldata, forKey: .calldata)
    }
}

