//
// Contract.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Contract: Codable, Hashable {

    public var code: String
    public var options: CompileOpts

    public init(code: String, options: CompileOpts) {
        self.code = code
        self.options = options
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case options
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(options, forKey: .options)
    }
}

