//
// DecodeCalldataBytecode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DecodeCalldataBytecode: Codable, Hashable {

    public enum Backend: String, Codable, CaseIterable {
        case fate = "fate"
        case aevm = "aevm"
    }
    /** Prefixed (cb_) Base64Check encoded byte array */
    public var calldata: String
    /** Prefixed (cb_) Base64Check encoded byte array */
    public var bytecode: String
    /** Compiler backend; fate | aevm */
    public var backend: Backend?

    public init(calldata: String, bytecode: String, backend: Backend? = nil) {
        self.calldata = calldata
        self.bytecode = bytecode
        self.backend = backend
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case calldata
        case bytecode
        case backend
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(calldata, forKey: .calldata)
        try container.encode(bytecode, forKey: .bytecode)
        try container.encodeIfPresent(backend, forKey: .backend)
    }
}

