//
// DryRunResults.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DryRunResults: Codable, Hashable {

    /** results */
    public var results: [DryRunResult]
    /** on-chain tx events */
    public var txEvents: [AnyCodable]?

    public init(results: [DryRunResult], txEvents: [AnyCodable]? = nil) {
        self.results = results
        self.txEvents = txEvents
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case results
        case txEvents = "tx_events"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(results, forKey: .results)
        try container.encodeIfPresent(txEvents, forKey: .txEvents)
    }
}

