//
// NameHash.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NameHash: Codable, Hashable {

    /** Base58Check encoded tagged value */
    public var nameId: String

    public init(nameId: String) {
        self.nameId = nameId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nameId = "name_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nameId, forKey: .nameId)
    }
}

