//
// NameEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NameEntry: Codable, Hashable {

    /** Base58Check encoded tagged value */
    public var id: String
    /** Base58Check encoded tagged pubkey */
    public var owner: String?
    public var ttl: ModelUInt64
    public var pointers: [NamePointer]

    public init(id: String, owner: String? = nil, ttl: ModelUInt64, pointers: [NamePointer]) {
        self.id = id
        self.owner = owner
        self.ttl = ttl
        self.pointers = pointers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case owner
        case ttl
        case pointers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(owner, forKey: .owner)
        try container.encode(ttl, forKey: .ttl)
        try container.encode(pointers, forKey: .pointers)
    }
}

