//
// ChannelSnapshotSoloTx.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChannelSnapshotSoloTx: Codable, Hashable {

    /** Base58Check encoded tagged pubkey */
    public var channelId: String
    /** Base58Check encoded tagged pubkey */
    public var fromId: String
    /** Base64Check encoded tagged byte array */
    public var payload: String
    public var ttl: ModelUInt64?
    public var fee: ModelUInt
    public var nonce: ModelUInt64?

    public init(channelId: String, fromId: String, payload: String, ttl: ModelUInt64? = nil, fee: ModelUInt, nonce: ModelUInt64? = nil) {
        self.channelId = channelId
        self.fromId = fromId
        self.payload = payload
        self.ttl = ttl
        self.fee = fee
        self.nonce = nonce
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case channelId = "channel_id"
        case fromId = "from_id"
        case payload
        case ttl
        case fee
        case nonce
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(channelId, forKey: .channelId)
        try container.encode(fromId, forKey: .fromId)
        try container.encode(payload, forKey: .payload)
        try container.encodeIfPresent(ttl, forKey: .ttl)
        try container.encode(fee, forKey: .fee)
        try container.encodeIfPresent(nonce, forKey: .nonce)
    }
}

