//
// ChannelSetDelegatesTx.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChannelSetDelegatesTx: Codable, Hashable {

    /** Base58Check encoded tagged pubkey */
    public var channelId: String
    /** Base58Check encoded tagged pubkey */
    public var fromId: String
    public var initiatorDelegateIds: [String]
    public var responderDelegateIds: [String]
    /** Base58Check encoded tagged pubkey */
    public var stateHash: String
    public var round: ModelUInt64
    /** Base64Check encoded tagged byte array */
    public var payload: String
    public var ttl: ModelUInt64?
    public var fee: ModelUInt
    public var nonce: ModelUInt64?

    public init(channelId: String, fromId: String, initiatorDelegateIds: [String], responderDelegateIds: [String], stateHash: String, round: ModelUInt64, payload: String, ttl: ModelUInt64? = nil, fee: ModelUInt, nonce: ModelUInt64? = nil) {
        self.channelId = channelId
        self.fromId = fromId
        self.initiatorDelegateIds = initiatorDelegateIds
        self.responderDelegateIds = responderDelegateIds
        self.stateHash = stateHash
        self.round = round
        self.payload = payload
        self.ttl = ttl
        self.fee = fee
        self.nonce = nonce
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case channelId = "channel_id"
        case fromId = "from_id"
        case initiatorDelegateIds = "initiator_delegate_ids"
        case responderDelegateIds = "responder_delegate_ids"
        case stateHash = "state_hash"
        case round
        case payload
        case ttl
        case fee
        case nonce
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(channelId, forKey: .channelId)
        try container.encode(fromId, forKey: .fromId)
        try container.encode(initiatorDelegateIds, forKey: .initiatorDelegateIds)
        try container.encode(responderDelegateIds, forKey: .responderDelegateIds)
        try container.encode(stateHash, forKey: .stateHash)
        try container.encode(round, forKey: .round)
        try container.encode(payload, forKey: .payload)
        try container.encodeIfPresent(ttl, forKey: .ttl)
        try container.encode(fee, forKey: .fee)
        try container.encodeIfPresent(nonce, forKey: .nonce)
    }
}

