//
// ChannelCloseMutualTx.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChannelCloseMutualTx: Codable, Hashable {

    /** Base58Check encoded tagged pubkey */
    public var channelId: String
    /** Base58Check encoded tagged pubkey */
    public var fromId: String
    public var initiatorAmountFinal: ModelUInt
    public var responderAmountFinal: ModelUInt
    public var ttl: ModelUInt64?
    public var fee: ModelUInt64
    public var nonce: ModelUInt64

    public init(channelId: String, fromId: String, initiatorAmountFinal: ModelUInt, responderAmountFinal: ModelUInt, ttl: ModelUInt64? = nil, fee: ModelUInt64, nonce: ModelUInt64) {
        self.channelId = channelId
        self.fromId = fromId
        self.initiatorAmountFinal = initiatorAmountFinal
        self.responderAmountFinal = responderAmountFinal
        self.ttl = ttl
        self.fee = fee
        self.nonce = nonce
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case channelId = "channel_id"
        case fromId = "from_id"
        case initiatorAmountFinal = "initiator_amount_final"
        case responderAmountFinal = "responder_amount_final"
        case ttl
        case fee
        case nonce
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(channelId, forKey: .channelId)
        try container.encode(fromId, forKey: .fromId)
        try container.encode(initiatorAmountFinal, forKey: .initiatorAmountFinal)
        try container.encode(responderAmountFinal, forKey: .responderAmountFinal)
        try container.encodeIfPresent(ttl, forKey: .ttl)
        try container.encode(fee, forKey: .fee)
        try container.encode(nonce, forKey: .nonce)
    }
}

