//
// ContractCallObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ContractCallObject: Codable, Hashable {

    /** Base58Check encoded tagged pubkey */
    public var callerId: String
    public var callerNonce: ModelUInt64
    public var height: ModelUInt64
    /** Base58Check encoded tagged pubkey */
    public var contractId: String
    public var gasPrice: ModelUInt
    public var gasUsed: ModelUInt64
    public var log: [Event]
    /** Base64Check encoded tagged byte array */
    public var returnValue: String
    /** The status of the call 'ok | error | revert'. */
    public var returnType: String

    public init(callerId: String, callerNonce: ModelUInt64, height: ModelUInt64, contractId: String, gasPrice: ModelUInt, gasUsed: ModelUInt64, log: [Event], returnValue: String, returnType: String) {
        self.callerId = callerId
        self.callerNonce = callerNonce
        self.height = height
        self.contractId = contractId
        self.gasPrice = gasPrice
        self.gasUsed = gasUsed
        self.log = log
        self.returnValue = returnValue
        self.returnType = returnType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case callerId = "caller_id"
        case callerNonce = "caller_nonce"
        case height
        case contractId = "contract_id"
        case gasPrice = "gas_price"
        case gasUsed = "gas_used"
        case log
        case returnValue = "return_value"
        case returnType = "return_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(callerId, forKey: .callerId)
        try container.encode(callerNonce, forKey: .callerNonce)
        try container.encode(height, forKey: .height)
        try container.encode(contractId, forKey: .contractId)
        try container.encode(gasPrice, forKey: .gasPrice)
        try container.encode(gasUsed, forKey: .gasUsed)
        try container.encode(log, forKey: .log)
        try container.encode(returnValue, forKey: .returnValue)
        try container.encode(returnType, forKey: .returnType)
    }
}

