//
// ContractObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ContractObject: Codable, Hashable {

    /** Base58Check encoded tagged pubkey */
    public var id: String
    /** Base58Check encoded tagged pubkey */
    public var ownerId: String
    public var vmVersion: ModelUInt16
    public var abiVersion: ModelUInt16
    public var active: Bool
    public var referrerIds: [String]
    public var deposit: ModelUInt64

    public init(id: String, ownerId: String, vmVersion: ModelUInt16, abiVersion: ModelUInt16, active: Bool, referrerIds: [String], deposit: ModelUInt64) {
        self.id = id
        self.ownerId = ownerId
        self.vmVersion = vmVersion
        self.abiVersion = abiVersion
        self.active = active
        self.referrerIds = referrerIds
        self.deposit = deposit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case ownerId = "owner_id"
        case vmVersion = "vm_version"
        case abiVersion = "abi_version"
        case active
        case referrerIds = "referrer_ids"
        case deposit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(ownerId, forKey: .ownerId)
        try container.encode(vmVersion, forKey: .vmVersion)
        try container.encode(abiVersion, forKey: .abiVersion)
        try container.encode(active, forKey: .active)
        try container.encode(referrerIds, forKey: .referrerIds)
        try container.encode(deposit, forKey: .deposit)
    }
}

