//
// DecodedCalldata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DecodedCalldata: Codable, Hashable {

    public var function: String
    public var arguments: [AnyCodable]

    public init(function: String, arguments: [AnyCodable]) {
        self.function = function
        self.arguments = arguments
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case function
        case arguments
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(function, forKey: .function)
        try container.encode(arguments, forKey: .arguments)
    }
}

