//
// DelegatesOneOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DelegatesOneOf: Codable, Hashable {

    public var initiator: [String]?
    public var responder: [String]?

    public init(initiator: [String]? = nil, responder: [String]? = nil) {
        self.initiator = initiator
        self.responder = responder
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case initiator
        case responder
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(initiator, forKey: .initiator)
        try container.encodeIfPresent(responder, forKey: .responder)
    }
}

