//
// DryRunAccount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DryRunAccount: Codable, Hashable {

    /** Base58Check encoded tagged pubkey */
    public var pubKey: String
    public var amount: ModelUInt

    public init(pubKey: String, amount: ModelUInt) {
        self.pubKey = pubKey
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pubKey = "pub_key"
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pubKey, forKey: .pubKey)
        try container.encode(amount, forKey: .amount)
    }
}

