//
// EncodedTx.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EncodedTx: Codable, Hashable {

    /** Base64Check encoded tagged byte array */
    public var tx: String

    public init(tx: String) {
        self.tx = tx
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tx
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tx, forKey: .tx)
    }
}

