//
// Event.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Event: Codable, Hashable {

    /** Base58Check encoded tagged pubkey */
    public var address: String
    /** Event topics */
    public var topics: [ModelUInt]
    /** Base64Check encoded tagged byte array */
    public var data: String

    public init(address: String, topics: [ModelUInt], data: String) {
        self.address = address
        self.topics = topics
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case topics
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encode(topics, forKey: .topics)
        try container.encode(data, forKey: .data)
    }
}

