//
// FateAssembler.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FateAssembler: Codable, Hashable {

    /** Fate assembler code */
    public var fateAssembler: String

    public init(fateAssembler: String) {
        self.fateAssembler = fateAssembler
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fateAssembler = "fate-assembler"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fateAssembler, forKey: .fateAssembler)
    }
}

