//
// FunctionCallInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FunctionCallInput: Codable, Hashable {

    /** (Possibly partial) Sophia contract code */
    public var source: String
    public var options: CompileOpts?
    /** Name of function to call */
    public var function: String
    /** Array of function call arguments */
    public var arguments: [String]

    public init(source: String, options: CompileOpts? = nil, function: String, arguments: [String]) {
        self.source = source
        self.options = options
        self.function = function
        self.arguments = arguments
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case source
        case options
        case function
        case arguments
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(source, forKey: .source)
        try container.encodeIfPresent(options, forKey: .options)
        try container.encode(function, forKey: .function)
        try container.encode(arguments, forKey: .arguments)
    }
}

