//
// Generation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Generation: Codable, Hashable {

    public var keyBlock: KeyBlock
    public var microBlocks: [String]

    public init(keyBlock: KeyBlock, microBlocks: [String]) {
        self.keyBlock = keyBlock
        self.microBlocks = microBlocks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case keyBlock = "key_block"
        case microBlocks = "micro_blocks"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(keyBlock, forKey: .keyBlock)
        try container.encode(microBlocks, forKey: .microBlocks)
    }
}

