//
// HashResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HashResponse: Codable, Hashable {

    public var hash: String

    public init(hash: String) {
        self.hash = hash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hash
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(hash, forKey: .hash)
    }
}

