//
// HeightResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HeightResponse: Codable, Hashable {

    public var height: ModelUInt64

    public init(height: ModelUInt64) {
        self.height = height
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case height
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(height, forKey: .height)
    }
}

