//
// NamePointer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NamePointer: Codable, Hashable {

    public var key: String
    /** Base58Check encoded tagged pubkey */
    public var id: String

    public init(key: String, id: String) {
        self.key = key
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(key, forKey: .key)
        try container.encode(id, forKey: .id)
    }
}

