//
// NameUpdateTx.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NameUpdateTx: Codable, Hashable {

    /** Base58Check encoded tagged value */
    public var nameId: String
    public var nameTtl: ModelUInt64
    public var pointers: [NamePointer]
    public var clientTtl: ModelUInt64
    public var fee: ModelUInt
    public var ttl: ModelUInt64?
    /** Base58Check encoded tagged pubkey */
    public var accountId: String
    public var nonce: ModelUInt64?

    public init(nameId: String, nameTtl: ModelUInt64, pointers: [NamePointer], clientTtl: ModelUInt64, fee: ModelUInt, ttl: ModelUInt64? = nil, accountId: String, nonce: ModelUInt64? = nil) {
        self.nameId = nameId
        self.nameTtl = nameTtl
        self.pointers = pointers
        self.clientTtl = clientTtl
        self.fee = fee
        self.ttl = ttl
        self.accountId = accountId
        self.nonce = nonce
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nameId = "name_id"
        case nameTtl = "name_ttl"
        case pointers
        case clientTtl = "client_ttl"
        case fee
        case ttl
        case accountId = "account_id"
        case nonce
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nameId, forKey: .nameId)
        try container.encode(nameTtl, forKey: .nameTtl)
        try container.encode(pointers, forKey: .pointers)
        try container.encode(clientTtl, forKey: .clientTtl)
        try container.encode(fee, forKey: .fee)
        try container.encodeIfPresent(ttl, forKey: .ttl)
        try container.encode(accountId, forKey: .accountId)
        try container.encodeIfPresent(nonce, forKey: .nonce)
    }
}

