//
// NameInfoOwnership.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NameInfoOwnership: Codable, Hashable {

    public var current: String?
    public var original: String?

    public init(current: String? = nil, original: String? = nil) {
        self.current = current
        self.original = original
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case current
        case original
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(current, forKey: .current)
        try container.encodeIfPresent(original, forKey: .original)
    }
}

