//
// NamePreclaimTx.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NamePreclaimTx: Codable, Hashable {

    /** Base58Check encoded tagged value */
    public var commitmentId: String
    public var fee: ModelUInt
    public var ttl: ModelUInt64?
    /** Base58Check encoded tagged pubkey */
    public var accountId: String
    public var nonce: ModelUInt64?

    public init(commitmentId: String, fee: ModelUInt, ttl: ModelUInt64? = nil, accountId: String, nonce: ModelUInt64? = nil) {
        self.commitmentId = commitmentId
        self.fee = fee
        self.ttl = ttl
        self.accountId = accountId
        self.nonce = nonce
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case commitmentId = "commitment_id"
        case fee
        case ttl
        case accountId = "account_id"
        case nonce
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(commitmentId, forKey: .commitmentId)
        try container.encode(fee, forKey: .fee)
        try container.encodeIfPresent(ttl, forKey: .ttl)
        try container.encode(accountId, forKey: .accountId)
        try container.encodeIfPresent(nonce, forKey: .nonce)
    }
}

