//
// OffChainDeposit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OffChainDeposit: Codable, Hashable {

    public var op: String
    /** Base58Check encoded tagged pubkey */
    public var from: String
    public var amount: ModelUInt

    public init(op: String, from: String, amount: ModelUInt) {
        self.op = op
        self.from = from
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case op
        case from
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(op, forKey: .op)
        try container.encode(from, forKey: .from)
        try container.encode(amount, forKey: .amount)
    }
}

