//
// OracleRegisterTx.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OracleRegisterTx: Codable, Hashable {

    public var queryFormat: String
    public var responseFormat: String
    public var queryFee: ModelUInt
    public var oracleTtl: TTL
    /** Base58Check encoded tagged pubkey */
    public var accountId: String
    public var nonce: ModelUInt64?
    public var fee: ModelUInt
    public var ttl: ModelUInt64?
    public var abiVersion: ModelUInt16?

    public init(queryFormat: String, responseFormat: String, queryFee: ModelUInt, oracleTtl: TTL, accountId: String, nonce: ModelUInt64? = nil, fee: ModelUInt, ttl: ModelUInt64? = nil, abiVersion: ModelUInt16? = nil) {
        self.queryFormat = queryFormat
        self.responseFormat = responseFormat
        self.queryFee = queryFee
        self.oracleTtl = oracleTtl
        self.accountId = accountId
        self.nonce = nonce
        self.fee = fee
        self.ttl = ttl
        self.abiVersion = abiVersion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case queryFormat = "query_format"
        case responseFormat = "response_format"
        case queryFee = "query_fee"
        case oracleTtl = "oracle_ttl"
        case accountId = "account_id"
        case nonce
        case fee
        case ttl
        case abiVersion = "abi_version"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(queryFormat, forKey: .queryFormat)
        try container.encode(responseFormat, forKey: .responseFormat)
        try container.encode(queryFee, forKey: .queryFee)
        try container.encode(oracleTtl, forKey: .oracleTtl)
        try container.encode(accountId, forKey: .accountId)
        try container.encodeIfPresent(nonce, forKey: .nonce)
        try container.encode(fee, forKey: .fee)
        try container.encodeIfPresent(ttl, forKey: .ttl)
        try container.encodeIfPresent(abiVersion, forKey: .abiVersion)
    }
}

