//
// OracleRespondTx.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OracleRespondTx: Codable, Hashable {

    /** Base58Check encoded tagged value */
    public var queryId: String
    public var response: String
    public var responseTtl: RelativeTTL
    public var fee: ModelUInt
    public var ttl: ModelUInt64?
    /** Base58Check encoded tagged pubkey */
    public var oracleId: String
    public var nonce: ModelUInt64?

    public init(queryId: String, response: String, responseTtl: RelativeTTL, fee: ModelUInt, ttl: ModelUInt64? = nil, oracleId: String, nonce: ModelUInt64? = nil) {
        self.queryId = queryId
        self.response = response
        self.responseTtl = responseTtl
        self.fee = fee
        self.ttl = ttl
        self.oracleId = oracleId
        self.nonce = nonce
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case queryId = "query_id"
        case response
        case responseTtl = "response_ttl"
        case fee
        case ttl
        case oracleId = "oracle_id"
        case nonce
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(queryId, forKey: .queryId)
        try container.encode(response, forKey: .response)
        try container.encode(responseTtl, forKey: .responseTtl)
        try container.encode(fee, forKey: .fee)
        try container.encodeIfPresent(ttl, forKey: .ttl)
        try container.encode(oracleId, forKey: .oracleId)
        try container.encodeIfPresent(nonce, forKey: .nonce)
    }
}

