//
// Peers.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Peers: Codable, Hashable {

    /** All discovered peers */
    public var peers: [String]
    /** All blocked peers */
    public var blocked: [String]

    public init(peers: [String], blocked: [String]) {
        self.peers = peers
        self.blocked = blocked
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case peers
        case blocked
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(peers, forKey: .peers)
        try container.encode(blocked, forKey: .blocked)
    }
}

