//
// PoI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PoI: Codable, Hashable {

    /** Base64Check encoded tagged byte array */
    public var poi: String

    public init(poi: String) {
        self.poi = poi
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case poi
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(poi, forKey: .poi)
    }
}

