//
// TxInfoObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TxInfoObject: Codable, Hashable {

    public var callInfo: ContractCallObject?
    public var gaInfo: GAObject?
    public var txInfo: String?

    public init(callInfo: ContractCallObject? = nil, gaInfo: GAObject? = nil, txInfo: String? = nil) {
        self.callInfo = callInfo
        self.gaInfo = gaInfo
        self.txInfo = txInfo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case callInfo = "call_info"
        case gaInfo = "ga_info"
        case txInfo = "tx_info"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(callInfo, forKey: .callInfo)
        try container.encodeIfPresent(gaInfo, forKey: .gaInfo)
        try container.encodeIfPresent(txInfo, forKey: .txInfo)
    }
}

